server:
  port: 8080
spring:
  application:
    name: "backend"
  devtools:
    add-properties: false
  r2dbc:
    name: backend
    username: parking
    password: q9GLNkHTCtFnTRZ79w5G
    url: r2dbc:postgresql://parking-db.ciuryss2jj1i.us-east-1.rds.amazonaws.com/postgres
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
